###
GET http://localhost:3000/restaurants

###

GET http://localhost:3000/restaurants/

###add review
POST http://localhost:3000/restaurants HTTP/1.1
Content-type: application/json

{
    
        "address":"2187",
        "review":"4.5 stars",
        "zip":"11224",
        "cuisine":"American",
        "name":"Riviera Caterer",
        "price":"$$",
        "street":"Stillwell Avenue"
            
}

###
PUT http://localhost:3000/restaurants/ HTTP/1.1
Content-Type: application/json

{
        "address":"2187",
        "review":"4.5 stars",
        "zip":"11224",
        "cuisine":"American",
        "name":"Riviera Caterer",
        "price":"$$",
        "street":"Stillwell Avenue"
        
}

###delete REVIEW
PUT http://localhost:3000/restaurants/

###


//PRODUCTION

###
GET https://bnb-reviews.onrender.com/restaurants

###

GET https://bnb-reviews.onrender.com/restaurants/6554bbdf646f4031efc8eacd

###add review
POST https://bnb-reviews.onrender.com/restaurants HTTP/1.1
Content-type: application/json

{
        "address":"1234",
        "review":"5 stars",
        "zip":"11225",
        "cuisine":"Italian",
        "name":"Pizza Spaghetti",
        "price":"$$$$$",
        "street":"Alphabet Avenue"
    
}

###
PUT https://bnb-reviews.onrender.com/restaurants/ HTTP/1.1
Content-Type: application/json

{
        "address":"2187",
        "review":"4.5 stars",
        "zip":"11224",
        "cuisine":"American",
        "name":"Riviera Caterer",
        "price":"$$",
        "street":"Stillwell Avenue"
    
}

###delete REVIEW
PUT https://bnb-reviews.onrender.com/restaurants/

###

