###
GET http://localhost:3000/reviews

###

GET http://localhost:3000/reviews/654d0d6f03454456cd0fd079

###add review
POST http://localhost:3000/reviews HTTP/1.1
Content-type: application/json

{
    "name"          : "NYC - Upper West Side Apt",
    "summary"       : "Murphey bed, super uncomfortable",
    "space"         : "",
    "description"  : "Apartment"
    
}

###
PUT http://localhost:3000/reviews/654d0d6f03454456cd0fd079 HTTP/1.1
Content-Type: application/json

{
    "name"          : "NYC - Upper West Side Apt",
    "summary"       : "Murphey bed, super uncomfortable",
    "space"         : "",
    "description"  : "Apartment"
    
}

###delete REVIEW
PUT http://localhost:3000/reviews/654d0d6f03454456cd0fd079

###

